spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/homeservices}
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}